<?php

use Core\ControlWeb;
use Core\G;

/**
 * Class UsersController
 */
class DataController extends ControlWeb
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        $model = new UserModel();
        var_dump($model->find()->one(['id' => 1]));
    }
}