<?php

use Core\ControlWeb;
use Core\Data;
use Core\G;

/**
 * Class UsersController
 */
class DataController extends ControlWeb
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        $model = new UserModel();
        var_dump($model->find()->one(['id' => 1]));
    }

    public function memAction()
    {
        Data::cache('default')->set('test-key', time());
        var_dump(Data::cache('default')->get('test-key'));
    }

    public function redisAction()
    {
        Data::redis('default')->set('test-key', time());
        var_dump(Data::redis('default')->get('test-key'));
    }
}