<?php

use Myaf\Core\G;
use \Yaf\Plugin_Abstract;
use Yaf\Request_Abstract;
use Yaf\Response_Abstract;

/**
 * Class StaticPlugin.
 * 静态文件下载插件.
 */
class StaticPlugin extends Plugin_Abstract
{
    public function routerShutdown(Request_Abstract $request, Response_Abstract $response)
    {
        parent::routerShutdown($request, $response); // TODO: Change the autogenerated stub

        if ($request->isCli()) {
            return;
        }

        if ($request->getControllerName() == 'Favicon.ico') {
            G::download('favicon.ico');
        } else {
            G::download($request->getBaseUri());
        }
    }
}