<html lang="zh-CN">
<head>
    <title>Home</title>
</head>
<body class="default-theme des-mat" style="background: rgb(255, 255, 255);">
<span id="prt"></span>
<div class="" id="lga">
    <div><h3>YAF FRAMEWORK :)</h3></div>
    <div>route: <b><?php echo $value;?></div>
    <div><hr></div>
    <div><h6>人生苦短,用laravel吧</h6></div>
    <div><h6>人生苦短,用python flask吧</h6></div>
    <div><h6>人生苦短,用golang gin吧</h6></div>
</div>


</body>
</html>